### ISSUE TITLE
I think we need issue template for our project

### ISSUE THREAD

**Issue by malker97** [Education-X/Education-X#16]
Here is the template that I find in other project, I think its pretty good for our project
## What is the current behavior?

Issue Number: N/A

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

-
-
-

**Comment by Windsooon** [comment]
LGTM, we can start from this verson

**Comment by Windsooon** [comment]
@malker97 Did you update this issue template?

**Comment by malker97** [comment]
fixed at #61
