### ISSUE TITLE
I think we need test data generator esp for code review

### ISSUE THREAD

**Issue by malker97** [Education-X/Education-X#22]
I'm require for the data generator for our project.
cuz I'm trying to make data generator for code review.
In my opinion, the structure of the comments for each article is roughly like this.
```
new_data = {
            'start_line': random.randint(1, 50),
            'end_line': random.randint(51, 100),
            'commit': commit,
            'date': datetime.datetime.now(),
            'reviewer': 'reviewer' + str(random.randint(1, 100)),
        }
```
do yall have any suggestion?

**Comment by Windsooon** [comment]
What does data generator mean? Do you mean the code review comments? If yes, I suggest using `start_index`, and `end_index`  here. What does 'commit': commit mean?

**Comment by malker97** [comment]
I think I had to close this branch because I seem to have had to split it up to keep our issues clear.
