### ISSUE TITLE
I think our file structure is not reasonable enough and I recommend to optimize our file structure.

### ISSUE THREAD

**Issue by malker97** [Education-X/Education-X#23]
I think the document structure of this project is not clear enough
I recommand we use file system like this:
```
Education-X
├── docs
├── src
 │   ├── back-end
 │   └── front-end
└── test
    └── db
```
If someone have other suggestion, plese add review at this issue

**Comment by Windsooon** [comment]
That's a great idea. You can create a PR for it.
