### ISSUE TITLE
Need Role-based login and registration system

### ISSUE THREAD

**Issue by wenliangchen** [Education-X/Education-X#27]
We are in need of a login and registration system that supports multiple roles (e.g. admin, moderator, regular user). Currently, our application does not have this capability and we would like to request it as a feature.

Specifically, we would like the following functionality:

- A user database table with fields for username, hashed password, email, and role
- A login form that allows users to enter their username and password, and checks the provided information against the user table
- A registration form that allows new users to create an account, including fields for username, password, email, and role
- Role-based authorization, so that certain actions can only be performed by users with the appropriate role

**Comment by Windsooon** [comment]
> A user database table with fields for username, hashed password, email, and role
Yes

> A login form that allows users to enter their username and password, and checks the provided information against the user table
Yes. 

> A registration form that allows new users to create an account, including fields for username, password, email, and role
I guess the user can't set their role by default. However, a superuser can edit the user's role in the django-admin platform

> Role-based authorization, so that certain actions can only be performed by users with the appropriate role
Maybe we can use https://docs.djangoproject.com/en/4.1/topics/auth/default/#groups to set up the role
