### ISSUE TITLE
Need Email Login and Password reset functionality

### ISSUE THREAD

**Issue by wenliangchen** [Education-X/Education-X#28]
We are in need of a login system that allows users to log in with their email address in addition to their username.

In addition, we would like to request a password reset feature that allows users to reset their password if they have forgotten it. This should include the following functionality:

- A password reset page that allows users to enter their email address
- A password reset email sent to the user's email address with a link to reset their password
- A password reset page that allows the user to enter a new password

**Comment by Windsooon** [comment]
@wenliangchen Yes, Please create a PR for it
