### ISSUE TITLE
[Feature]We need to add a Python dependency for MongoDB.

### ISSUE THREAD

**Issue by malker97** [Education-X/Education-X#36]
I think we should introduce pymongo to support MongoDB.  If anyone else has a better Python package please let me know.

**Comment by Windsooon** [comment]
Why did we choose MongoDB? We didn't discuss which database we are going to use, right? Tell me the reason you choose MongoDB instead of other database.

**Comment by malker97** [comment]
I can abstract your question to what we chose NoSQL database, in fact, we didn't choose a traditional database because of the decision of our whole code-review team, we decided to use NoSQL because NoSQL can do everything we need for SQL and it can be iterated quickly (or because it has higher scalability and better performance because they don't require strict schema definition and relational maintenance). As for why we choose MongoDB, the fundamental reason is that most cloud platforms can support MongoDB very well, not only that, the open source community also provides very right graphical plug-ins or related container projects for Mongo, which makes MongoDB very easy to manage.

**Comment by Windsooon** [comment]
@malker97 I agree that MongoDB would be a good option for this platform. However, In this version, we would only use a SQL database for easy development and maintenance.
