### ISSUE TITLE
We need update for CI, If we use new folder structure

### ISSUE THREAD

**Issue by malker97** [Education-X/Education-X#64]
If we use a new folder structure as I said in #23, I think we also need to update the CI file for our backend.

**Comment by Windsooon** [comment]
We need `docs` and `src`, inside the `src` folder, Do we need `backend` and `frontend`? I'm not sure what kind of files we will put into frontend since we only use Vue and some CSS/JS which should put into `static` folder.

**Comment by malker97** [comment]
I updated my file structure based on Windson's reply #64, do yall have any other suggestions for this?
```
Education-X
├── docs
├── src
│   └── this-folder-will-save-all-codes
├── static
│   └── save-vue-html-css
└── test
    └── db

```

**Comment by malker97** [comment]
I think I know what the file tree you want looks like.
```
Education-X
├── docs
├── src
│   ├── static
│   │   └── save-vue-html-template-with-cdn
│   └── this-folder-will-save-all-codes
└── test
    ├── be
    ├── db
    └── fe
```
