### ISSUE TITLE
[Feature] Basic user login function with django-rest-framework

### ISSUE THREAD

**Issue by Thinkpeach-a** [Education-X/Education-X#71]
Implement the basic register and login with dj-rest-auth component

**Comment by Windsooon** [comment]
We are not going to use dj-rest-auth in our project right not.

**Comment by Windsooon** [comment]
We are not going to use dj-rest-auth in our project right now.

**Comment by Windsooon** [comment]
We are not going to use dj-rest-auth in our project right now.

**Comment by Thinkpeach-a** [comment]
We abandon the rest-api implement
